name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install anybadge
      - name: Generate dummy badge
        run: |
          anybadge -l Version -v 1.2.3 -f pytest_coverage.svg
        
        
      - name: Upload GitHub Badges
        uses: actions/upload-artifact@v4
        with:
          name: pytest_coverage.svg
          path: pytest_coverage.svg          
